### ISSUE TITLE
Login failing with 403 Permission Denied

### ISSUE THREAD

**Issue by henworth** [happyleavesaoc/python-upsmychoice#3]
In trying to setup the UPS Home Assistant sensor, I'm seeing the login requests being blocked and receive a 403 Permission Denied instead of the expected 302. This case doesn't seem to be caught so it manifests later on when trying to get packages as `upsmychoice.UPSError: failed to find token or tid`.

I tried sending extra headers (user agent, etc.) but I'm not able to get a successful login.

**Comment by happyleavesaoc** [comment]
UPS updated their login procedure. I will push a fix today.
